server {
    listen 80;
    client_max_body_size 20M;
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.htmll;
    }

    location /send/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /files.html;
    }
    # location / {
    #     root /usr/share/nginx/html;
    #     try_files $uri $uri/ /login.html;}
    location /success/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /success.html;
    }
    location /saitid {
    proxy_pass http://api:8000/saitid;
    }

    location /cookie/ {
        proxy_pass http://api:8000/cookie/ ;
    }
      location /docs {
        proxy_pass http://api:8000/docs;
    }

    location /openapi.json {
        proxy_pass http://api:8000/openapi.json;
    }
    location /api/ {
        proxy_pass http://api:8000/api/;
    }
}
