"""initial

Revision ID: 7e9c61a604d5
Revises: 
Create Date: 2026-02-17 00:38:57.518103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e9c61a604d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('time_finish', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('site_id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('sending',
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('time_send', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('site_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sending')
    op.drop_table('requests')
    # ### end Alembic commands ###
