"""new table

Revision ID: f66916ae964b
Revises: 
Create Date: 2026-02-21 20:08:19.236491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f66916ae964b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('get_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('time_send', sa.String(), nullable=True),
    sa.Column('Sending', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('time_finish', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('site_id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('sending',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('time_send', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('swap_id_kd',
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('kd_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swap_id_kd')
    op.drop_table('sending')
    op.drop_table('requests')
    op.drop_table('get_file')
    # ### end Alembic commands ###
