"""add is_sent column

Revision ID: f66916ae964d
Revises: f66916ae964c
Create Date: 2026-02-28 21:01:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f66916ae964d'
down_revision: Union[str, None] = 'f66916ae964c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('text_messages', sa.Column('is_sent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('text_messages', 'is_sent')
    # ### end Alembic commands ###
