server {
    listen 80;
    client_max_body_size 20M;
    server_name kaicloud.ru;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name kaicloud.ru;

    ssl_certificate /etc/nginx/certs/certificate_ca.crt;
    ssl_certificate_key /etc/nginx/certs/certificate.key;


    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;  # Исправлено!
    }

    location /send/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /files.html;
    }
    
    location /api {
        proxy_pass http://api:8000/api;  # Для Docker api
    }
    location /docs {
        proxy_pass http://api:8000/docs;  # Для Docker api
    }

    location /openapi.json {
        proxy_pass http://api:8000/openapi.json;
    }
}

