[Interface]
PrivateKey = +AtnH7PIFq3R72r9KhEWshcufvAIQ/CtaeJku7nhy3A=
Address = 10.66.66.39/32,fd42:42:42::39/128
DNS = 94.140.14.14,94.140.15.15

[Peer]
PublicKey = aRIc7xuQAcEAYkZx/dx2QP+ckP0ClE4tXdpFIKYhIk0=
PresharedKey = OBp1JXGc7KygSyUW5fwTOiF9uEOZkzuw7tjO3lp/J1k=
Endpoint = 185.39.204.125:51722
AllowedIPs = 0.0.0.0/0,::/0
